# Usamos la versión CLI de PHP, que es más ligera para tareas de consola
FROM php:8.2-cli

# Instalación de extensiones necesarias:
# pdo_pgsql: Para interactuar con la DB Master
# amqp: Para conectarse a RabbitMQ
RUN apt-get update \
    && apt-get install -y libpq-dev librabbitmq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && pecl install amqp \
    && docker-php-ext-enable amqp \
    && rm -rf /var/lib/apt/lists/*

# Directorio de trabajo
WORKDIR /app

# Copiamos el script del consumidor
# La ruta 'src/worker/consumer.php' es relativa a la raíz del repositorio
COPY src/worker/consumer.php /app/consumer.php

# Comando para ejecutar el worker de forma continua
CMD ["php", "consumer.php"]